name: CI

on:
  pull_request:
    paths:
      - '1-DevOps/idempotweet/**'
  workflow_call:
defaults:
  run:
    working-directory: 1-DevOps/idempotweet
jobs:
  ci:

    name: ci
    runs-on: ${{ vars.RUNNER || 'self-hosted' }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: corepack enable
        working-directory: .
      - run: yarn install --immutable
      - run: yarn test
      - run: yarn test:coverage
      - uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: 1-DevOps/idempotweet
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}